### ISSUE TITLE
Run command from history?

### ISSUE THREAD

**Issue by bomberstudios** [natethinks/jog#1]
Thanks for creating this, I love a simple tool (yay for one liners!)

I may be missing something, but it’d be nice to have an easy way to run one of the commands in the history.

This would probably turn this into a not-a-one-liner-anymore, and maybe ZSH already has a way to turn that list into something runnable, but something like this would be cool (for me, at least 😅):

```
$> jog
1. ls -la
2. make
3. make clean
4. sudo rm -rf /

Type a number to run the command again, any other key to exit: [ ]
```

Alternatively, the ability to run a command with `jog 3` would also be interesting.

Again, thanks for sharing!

**Comment by khughitt** [comment]
```
alias jg='eval `jog | fzf`'
```

**Comment by DmitrySandalov** [comment]
Just wrote a [Zaw](https://github.com/zsh-users/zaw) source: [DmitrySandalov/zaw-jog](https://github.com/DmitrySandalov/zaw-jog)

**Comment by natethinks** [comment]
Love that alias solution. I'm going to close this because jog being a unix style solution, it's easily extensible by piping the output to anything you want.

**Comment by bomberstudios** [comment]
Nice, thanks!
