### ISSUE TITLE
Jog will fail for any history that has a pipe in it.

### ISSUE THREAD

**Issue by FearTheBadger** [natethinks/jog#3]
If I have a historical entry `cat test | grep word` when you run `jog` your output would be: 

``` command
$ jog
cat test
```
instead of
``` command
$ jog
cat test | grep word
```

suggestion to use a special character for the break.
Something like: `⋮`

**Comment by natethinks** [comment]
Vertical ellipsis, that's a great idea. You could make the change and send me a PR if you want, I'll get to it later this week if not.

**Comment by hjorthjort** [comment]
or you could use `sed` instead of `cut`:
```
sed -e "s/|[^\|]*$//"
```
This will find the last pipe. So will work as long as your *path* doesn't have a pipe in it.

**Comment by FearTheBadger** [comment]
https://github.com/natethinks/jog/pull/4
