### ISSUE TITLE
What does jog mean?

### ISSUE THREAD

**Issue by augnustin** [natethinks/jog#8]
I don't get where the name comes from. Which is important to remember using new aliases. 

How about `herestory`? Or `cwdhist`? Something else?

**Comment by AnimiVulpis** [comment]
I assume the name was choosen because of the "**jog your memory**" idiom:

[reference](https://idioms.thefreedictionary.com/jog+your+memory)

**Comment by natethinks** [comment]
Correct. As used in the gif included in the README. You can rename it to anything you like when you copy the script to your machine.
